from src.calculate_distance import haversine_distance
from database.clean_data import haversine_distance
from database.insert_data import haversine_distance
from src.request_cep import haversine_distance
